repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/timothycrosley/isort
    rev: master
    hooks:
    - id: isort
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
